# Generated by Django 4.1 on 2024-11-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidoPaterno', models.CharField(max_length=25)),
                ('apellidoMaterno', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=40)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cajero', 'Cajero')], max_length=25)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=10)),
                ('montoPagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaVenta', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=25)),
                ('costoProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margenGanancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockActual', models.IntegerField()),
                ('stockUmbral', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuentoPorcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadVendida', models.IntegerField()),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalProducto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoEfectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montoTarjeta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalVentas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCierre', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario')),
            ],
        ),
    ]
